# Generated by Django 3.0.8 on 2020-07-04 01:05

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Real name strongly encouraged.  However, if necessary use a descriptor like 'Concerned Parent' or 'Father of Two'. (Required)", max_length=255)),
                ('email', models.EmailField(help_text="Your email is private and not shared.  It's used to manage preferences and send adminstrative updates. (Required)", max_length=254, unique=True)),
                ('location', models.CharField(choices=[('ath', 'Atherton'), ('bel', 'Belmont'), ('brb', 'Brisbane'), ('bur', 'Burlingame'), ('col', 'Colma'), ('dc', 'Daly City'), ('epa', 'East Palo Alto'), ('fc', 'Foster City'), ('hmb', 'Half Moon Bay'), ('hil', 'Hillsborough'), ('mp', 'Menlo Park'), ('mil', 'Millbrae'), ('pac', 'Pacifica'), ('pv', 'Portola Valley'), ('rc', 'Redwood City'), ('sb', 'San Bruno'), ('sc', 'San Carlos'), ('sm', 'San Mateo'), ('ssf', 'South San Francisco'), ('ws', 'Woodside'), ('un', 'Unincorporated San Mateo County'), ('out', 'Outside of San Mateo County')], help_text='Your city. (Required)', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Your mobile phone. (Optional)', max_length=255)),
                ('is_volunteer', models.BooleanField(default=False, help_text="If you're willing to volunteer in some manner please check this box. ")),
                ('is_teacher', models.BooleanField(default=False, help_text="If you're an educator please check this box. ")),
                ('is_doctor', models.BooleanField(default=False, help_text="If you're a physician please check this box. ")),
                ('notes', models.TextField(blank=True, default=None, help_text='Feel free to include private notes just for us.', max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(max_length=255)),
                ('status', models.TextField(blank=True)),
                ('schedule', models.IntegerField(choices=[(0, '(Unknown)'), (10, 'In-Person'), (20, 'Blended'), (30, 'Distance'), (40, 'Undecided')], default=0, null=True)),
                ('masks', models.IntegerField(choices=[(0, '(Unknown)'), (10, 'Required'), (20, 'Optional'), (30, 'Disallowed')], default=0, null=True)),
                ('is_masks', models.BooleanField(default=True)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('num', models.IntegerField(default=50)),
                ('question', models.TextField(max_length=255)),
                ('answer', models.TextField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'New'), (10, 'Open'), (20, 'Delivered')], default=0)),
                ('text', models.TextField(blank=True, max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to='app.District')),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'New'), (10, 'Signed'), (20, 'Removed')], default=0)),
                ('name', models.CharField(help_text="Real name strongly encouraged.  However, if necessary use a descriptor like 'Concerned Parent' or 'Father of Two'. (Required)", max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False, help_text='List My Name on the Website.')),
                ('message', models.TextField(blank=True, help_text='Feel free to include a public message attached to your signature.', max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='app.Account')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='app.Petition')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.IntegerField(blank=True, choices=[(10, 'Superintendent'), (20, 'Board President'), (30, 'Board Vice-President'), (40, 'Board Clerk'), (50, 'Board Trustee')], null=True)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.District')),
            ],
        ),
    ]
