# Generated by Django 3.0.8 on 2020-07-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Petition',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='department',
            new_name='petition',
        ),
        migrations.RenameField(
            model_name='signature',
            old_name='department',
            new_name='petition',
        ),
    ]
