# Generated by Django 3.0.7 on 2020-07-01 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Real name strongly encouraged.  However, if necessary use a descriptor like 'Concerned Parent' or 'Father of Two'. (Required)", max_length=255)),
                ('location', models.CharField(choices=[('ath', 'Atherton'), ('bel', 'Belmont'), ('brb', 'Brisbane'), ('bur', 'Burlingame'), ('col', 'Colma'), ('dc', 'Daly City'), ('epa', 'East Palo Alto'), ('fc', 'Foster City'), ('hmb', 'Half Moon Bay'), ('hil', 'Hillsborough'), ('mp', 'Menlo Park'), ('mil', 'Millbrae'), ('pac', 'Pacifica'), ('pv', 'Portola Valley'), ('rc', 'Redwood City'), ('sb', 'San Bruno'), ('sc', 'San Carlos'), ('sm', 'San Mateo'), ('ssf', 'South San Francisco'), ('ws', 'Woodside'), ('un', 'Unincorporated San Mateo County'), ('out', 'Outside of San Mateo County')], help_text='Your city. (Required)', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Your mobile phone. (Optional)', max_length=255, null=True)),
                ('is_volunteer', models.BooleanField(default=False, help_text="If you're willing to volunteer in some manner please check this box. ")),
                ('is_teacher', models.BooleanField(default=False, help_text="If you're an educator please check this box. ")),
                ('is_doctor', models.BooleanField(default=False, help_text="If you're a physician please check this box. ")),
                ('email', models.EmailField(help_text="Your email is private and not shared.  It's used to manage preferences and send adminstrative updates. (Required)", max_length=254, null=True, unique=True)),
                ('notes', models.TextField(blank=True, default=None, help_text='Feel free to include private notes just for us.', max_length=512, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
