# Generated by Django 3.0.7 on 2020-06-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signature',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
