# Generated by Django 3.0.7 on 2020-06-13 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200613_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='handle',
            field=models.CharField(blank=True, help_text="Your public name is how it will appear on the website.  This could be your real name (which is the most powerful), or first name initial last name, or something like 'Father of Two'.  If blank, defaults to your real name.", max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('ATH', 'Atherton'), ('BEL', 'Belmont'), ('BRB', 'Brisbane'), ('BUR', 'Burlingame'), ('COL', 'Colma'), ('DC', 'Daly City'), ('EPA', 'East Palo Alto'), ('FC', 'Foster City'), ('HMB', 'Half Moon Bay'), ('HIL', 'Hillsborough'), ('MP', 'Menlo Park'), ('MIL', 'Millbrae'), ('PAC', 'Pacifica'), ('PV', 'Portola Valley'), ('RC', 'Redwood City'), ('SB', 'San Bruno'), ('SC', 'San Carlos'), ('SM', 'San Mateo'), ('SSF', 'South San Francisco'), ('WS', 'Woodside'), ('UN', 'Unincorporated San Mateo County'), ('OUT', 'Outside of San Mateo County')], help_text='This helps provide specificity to Mr. Callagy.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Concerned Parent', help_text="Be aware your real name makes a real a difference.  However, we recognize the need for privacy so use something like 'Concerned Parent' or 'Father of Two' if you feel you must.  Your signature will be part of the public record.", max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.TextField(blank=True, default=None, help_text='Feel free to include anything you think we should know.  For instance, many have used this box to indicate they are teachers who are supportive of starting normal -- and we love to hear that!', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text="Your email is private and not shared.  We need it to manage preferences and send updates.  If you do not wish updates, unclick the 'Send Updates' checkbox.", max_length=254, unique=True),
        ),
    ]
