# Generated by Django 3.0.7 on 2020-07-01 11:28

from django.db import migrations

def forward(apps, schema_editor):
    Account = apps.get_model('app.account')
    Signature = apps.get_model('app.signature')
    User = apps.get_model('app.user')

    ss = Signature.objects.all()
    for s in ss:
        a = Account.objects.create(
            name=s.name,
            location=s.location,
            phone=s.phone,
            is_volunteer=s.is_volunteer,
            is_teacher=s.is_teacher,
            is_doctor=s.is_doctor,
            email=s.email,
            notes=s.notes,
            user=s.user,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
