# Generated by Django 3.0.7 on 2020-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200605_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
