# Generated by Django 3.0.8 on 2020-07-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='text',
            field=models.TextField(),
        ),
    ]
