# Generated by Django 3.0.8 on 2020-07-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200725_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Your Student's name will be shown to other parents on the private site; it will not appear on the public site.  ", max_length=100),
        ),
    ]
