# Generated by Django 3.0.8 on 2020-07-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200708_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_public',
            field=models.BooleanField(default=False, help_text='List name on website.'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_subscribe',
            field=models.BooleanField(default=False, help_text='Subscribe for updates.'),
        ),
    ]
