# Generated by Django 3.0.8 on 2020-07-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='homeroom',
            constraint=models.UniqueConstraint(fields=('grade', 'school'), name='unique_homeroom'),
        ),
    ]
