# Generated by Django 3.0.8 on 2020-07-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200703_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, choices=[('ath', 'Atherton'), ('bel', 'Belmont'), ('brb', 'Brisbane'), ('bur', 'Burlingame'), ('col', 'Colma'), ('dc', 'Daly City'), ('epa', 'East Palo Alto'), ('fc', 'Foster City'), ('hmb', 'Half Moon Bay'), ('hil', 'Hillsborough'), ('mp', 'Menlo Park'), ('mil', 'Millbrae'), ('pac', 'Pacifica'), ('pv', 'Portola Valley'), ('rc', 'Redwood City'), ('sb', 'San Bruno'), ('sc', 'San Carlos'), ('sm', 'San Mateo'), ('ssf', 'South San Francisco'), ('ws', 'Woodside'), ('un', 'Unincorporated San Mateo County'), ('out', 'Outside of San Mateo County')], help_text='Your city. (Required)', max_length=255),
        ),
    ]
