# Generated by Django 3.0.7 on 2020-06-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200606_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='location',
            field=models.CharField(blank=True, choices=[('ATH', 'Atherton'), ('BEL', 'Belmont'), ('BRB', 'Brisbane'), ('BUR', 'Burlingame'), ('COL', 'Colma'), ('DC', 'Daly City'), ('EPA', 'East Palo Alto'), ('FC', 'Foster City'), ('HMB', 'Half Moon Bay'), ('HIL', 'Hillsborough'), ('MP', 'Menlo Park'), ('MIL', 'Millbrae'), ('PAC', 'Pacifica'), ('PV', 'Portola Valley'), ('RC', 'Redwood City'), ('SB', 'San Bruno'), ('SC', 'San Carlos'), ('SSF', 'South San Francisco'), ('WS', 'Woodside'), ('UN', 'Unincorporated SMC'), ('OUT', 'Outside of SMC')], max_length=255, null=True),
        ),
    ]
