# Generated by Django 3.0.8 on 2020-07-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200704_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_doctor',
            field=models.BooleanField(default=False, help_text="If you're a physician please check this box."),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text="If you're an educator please check this box."),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_volunteer',
            field=models.BooleanField(default=False, help_text="If you're willing to volunteer please check this box."),
        ),
        migrations.AlterField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Feel free to include private notes just for us.', max_length=512),
        ),
        migrations.AlterField(
            model_name='signature',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Feel free to include a public message attached to your signature.', max_length=512),
        ),
    ]
