# Generated by Django 3.0.8 on 2020-07-03 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200702_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='app.Account'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature', to=settings.AUTH_USER_MODEL),
        ),
    ]
