# Generated by Django 3.0.8 on 2020-07-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200725_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='parent',
            name='state',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
