# Generated by Django 3.0.8 on 2020-07-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200704_1318'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='signature',
            constraint=models.UniqueConstraint(fields=('account', 'petition'), name='unique_signature'),
        ),
    ]
