# Generated by Django 3.0.8 on 2020-07-03 13:45

from django.db import migrations

def forward(apps, schema_editor):
    Account = apps.get_model('app.account')
    Signature = apps.get_model('app.signature')

    ss = Signature.objects.all()
    for s in ss:
        a = Account.objects.get(
            email=s.email
        )
        s.account = a
        s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200703_0644'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
