# Generated by Django 3.0.7 on 2020-06-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200606_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='preferences',
            field=models.CharField(blank=True, choices=[('INIT', 'Intials Only'), ('PUB', 'Full Name'), ('ANON', 'Anonymous')], max_length=255, null=True),
        ),
    ]
