# Generated by Django 3.0.8 on 2020-07-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200703_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='district',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='is_volunteer',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='user',
        ),
        migrations.AlterField(
            model_name='signature',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='app.Account'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='message',
            field=models.TextField(blank=True, help_text='Feel free to include a public message attached to your signature.', max_length=512),
        ),
    ]
