# Generated by Django 3.0.7 on 2020-06-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_signature_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signature',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
