# Generated by Django 3.0.8 on 2020-07-25 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200725_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='homeroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.Homeroom'),
        ),
    ]
