# Generated by Django 3.0.8 on 2020-07-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200725_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='(Unknown)', help_text="Your Student's name will be shown to other parents on the private site; it will not appear on the public site.  ", max_length=100),
        ),
    ]
