# Generated by Django 3.0.8 on 2020-07-03 14:21

from django.db import migrations

def forward(apps, schema_editor):
    Account = apps.get_model('app.account')
    Signature = apps.get_model('app.signature')

    ss = Signature.objects.filter(location=None)
    ss.update(location='')

    cs = Account.objects.filter(email=None)
    cs.update(email='')
    cs = Account.objects.filter(location=None)
    cs.update(location='')
    cs = Account.objects.filter(notes=None)
    cs.update(notes='')
    cs = Account.objects.filter(phone=None)
    cs.update(phone='')

class Migration(migrations.Migration):


    dependencies = [
        ('app', '0007_auto_20200703_0706'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
