# Generated by Django 3.0.8 on 2020-07-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200704_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='district',
            name='admin_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='district',
            name='admin_first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='district',
            name='admin_last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='district',
            name='cd_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='district',
            name='county_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='district',
            name='district_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='district',
            name='doc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='nces_district_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='district',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='district',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
