# Generated by Django 3.0.8 on 2020-07-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200709_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_public',
            field=models.BooleanField(default=True, help_text='List name on website.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_subscribe',
            field=models.BooleanField(default=True, help_text='Subscribe for updates.'),
        ),
    ]
