# Generated by Django 3.0.8 on 2020-07-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200703_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(help_text="Your email is private and not shared.  It's used to manage preferences and send adminstrative updates. (Required)", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.CharField(choices=[('ath', 'Atherton'), ('bel', 'Belmont'), ('brb', 'Brisbane'), ('bur', 'Burlingame'), ('col', 'Colma'), ('dc', 'Daly City'), ('epa', 'East Palo Alto'), ('fc', 'Foster City'), ('hmb', 'Half Moon Bay'), ('hil', 'Hillsborough'), ('mp', 'Menlo Park'), ('mil', 'Millbrae'), ('pac', 'Pacifica'), ('pv', 'Portola Valley'), ('rc', 'Redwood City'), ('sb', 'San Bruno'), ('sc', 'San Carlos'), ('sm', 'San Mateo'), ('ssf', 'South San Francisco'), ('ws', 'Woodside'), ('un', 'Unincorporated San Mateo County'), ('out', 'Outside of San Mateo County')], help_text='Your city. (Required)', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True, default=None, help_text='Feel free to include private notes just for us.', max_length=512),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, help_text='Your mobile phone. (Optional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='signature',
            name='location',
            field=models.CharField(choices=[('ath', 'Atherton'), ('bel', 'Belmont'), ('brb', 'Brisbane'), ('bur', 'Burlingame'), ('col', 'Colma'), ('dc', 'Daly City'), ('epa', 'East Palo Alto'), ('fc', 'Foster City'), ('hmb', 'Half Moon Bay'), ('hil', 'Hillsborough'), ('mp', 'Menlo Park'), ('mil', 'Millbrae'), ('pac', 'Pacifica'), ('pv', 'Portola Valley'), ('rc', 'Redwood City'), ('sb', 'San Bruno'), ('sc', 'San Carlos'), ('sm', 'San Mateo'), ('ssf', 'South San Francisco'), ('ws', 'Woodside'), ('un', 'Unincorporated San Mateo County'), ('out', 'Outside of San Mateo County')], help_text='Your city. (Required)', max_length=255),
        ),
    ]
