# Generated by Django 3.0.8 on 2020-07-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200705_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='cd_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='nces_district_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
