# Generated by Django 3.0.8 on 2020-07-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200709_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='name',
        ),
        migrations.AlterField(
            model_name='signature',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (10, 'Signed'), (20, 'Removed')], default=10),
        ),
    ]
