# Generated by Django 3.0.7 on 2020-06-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='email',
            field=models.EmailField(help_text="Your email is private and not shared.  We need it to manage preferences and send updates.  If you do not wish updates, unclick the 'Send Updates' checkbox.", max_length=254, null=True, unique=True),
        ),
    ]
