# Generated by Django 3.0.7 on 2020-06-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200606_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
