# Generated by Django 3.0.8 on 2020-07-28 18:43

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200728_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('location', models.IntegerField(choices=[(0, 'New'), (10, 'Invited'), (20, 'Accepted')], default=0)),
                ('homeroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classmates', to='app.Homeroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classmates', to='app.Student')),
            ],
        ),
    ]
