# Generated by Django 3.0.8 on 2020-07-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200709_2123'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='signature',
            name='unique_signature',
        ),
    ]
