# Generated by Django 3.0.7 on 2020-06-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customuser_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
