# Generated by Django 3.0.8 on 2020-07-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_petition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='target',
        ),
    ]
