# Generated by Django 3.0.7 on 2020-06-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200606_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
