# Generated by Django 3.0.8 on 2020-07-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200705_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='cd_status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
