# Generated by Django 3.0.8 on 2020-07-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_classmate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classmate',
            old_name='location',
            new_name='status',
        ),
    ]
