# Generated by Django 3.0.7 on 2020-06-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200614_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='signature',
            old_name='timestamp',
            new_name='created',
        ),
    ]
