# Generated by Django 3.0.7 on 2020-06-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_signature_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='website',
            new_name='handle',
        ),
    ]
