# Generated by Django 3.0.8 on 2020-07-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_signature_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='signature',
            constraint=models.UniqueConstraint(fields=('user', 'petition'), name='unique_signature'),
        ),
    ]
