# Generated by Django 3.0.8 on 2020-07-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200728_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeroom',
            old_name='owner',
            new_name='parent',
        ),
    ]
