# Generated by Django 3.0.8 on 2020-07-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_petition_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='petition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='app.Petition'),
        ),
    ]
