# Generated by Django 3.0.8 on 2020-07-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200705_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='cd_status',
        ),
    ]
