# Generated by Django 3.0.8 on 2020-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200728_1451'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='homeroom',
            name='unique_homeroom',
        ),
        migrations.AlterField(
            model_name='homeroom',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (10, 'Open'), (20, 'Closed')], default=0),
        ),
    ]
