# Generated by Django 3.0.8 on 2020-07-10 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200710_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='account',
        ),
        migrations.AlterField(
            model_name='contact',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.Petition'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='app.Petition'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
