# Generated by Django 3.0.8 on 2020-07-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_signature_petition'),
    ]

    operations = [
    ]
