# Generated by Django 3.0.7 on 2020-06-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200614_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='district',
            field=models.CharField(blank=True, choices=[('ATH', 'Atherton'), ('BEL', 'Belmont'), ('BRB', 'Brisbane'), ('BUR', 'Burlingame'), ('COL', 'Colma'), ('DC', 'Daly City'), ('EPA', 'East Palo Alto'), ('FC', 'Foster City'), ('HMB', 'Half Moon Bay'), ('HIL', 'Hillsborough'), ('MP', 'Menlo Park'), ('MIL', 'Millbrae'), ('PAC', 'Pacifica'), ('PV', 'Portola Valley'), ('RC', 'Redwood City'), ('SB', 'San Bruno'), ('SC', 'San Carlos'), ('SM', 'San Mateo'), ('SSF', 'South San Francisco'), ('WS', 'Woodside'), ('UN', 'Unincorporated San Mateo County'), ('OUT', 'Outside of San Mateo County')], help_text='Your school district. (Optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='is_doctor',
            field=models.BooleanField(default=False, help_text="If you're a physician check this box. "),
        ),
        migrations.AddField(
            model_name='signature',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text="If you're an educator check this box. "),
        ),
        migrations.AlterField(
            model_name='signature',
            name='email',
            field=models.EmailField(help_text="Your email is private and not shared.  We need it to manage preferences and send updates.  If you do not wish updates, unclick the 'Send Updates' checkbox. (Required)", max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If you would like your name listed on the Start Normal website so others can see, please check this box.'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='is_volunteer',
            field=models.BooleanField(default=False, help_text="If you're willing to volunteer in some manner check this box. "),
        ),
        migrations.AlterField(
            model_name='signature',
            name='location',
            field=models.CharField(choices=[('ATH', 'Atherton'), ('BEL', 'Belmont'), ('BRB', 'Brisbane'), ('BUR', 'Burlingame'), ('COL', 'Colma'), ('DC', 'Daly City'), ('EPA', 'East Palo Alto'), ('FC', 'Foster City'), ('HMB', 'Half Moon Bay'), ('HIL', 'Hillsborough'), ('MP', 'Menlo Park'), ('MIL', 'Millbrae'), ('PAC', 'Pacifica'), ('PV', 'Portola Valley'), ('RC', 'Redwood City'), ('SB', 'San Bruno'), ('SC', 'San Carlos'), ('SM', 'San Mateo'), ('SSF', 'South San Francisco'), ('WS', 'Woodside'), ('UN', 'Unincorporated San Mateo County'), ('OUT', 'Outside of San Mateo County')], help_text='Please provide your city. (Required)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='name',
            field=models.CharField(help_text="Be aware your real name makes a real a difference.  However, we recognize the need for privacy so use something like 'Concerned Parent' or 'Father of Two' if you must.  This name will become part of the public record when the signatures are submitted. (Required)", max_length=255),
        ),
        migrations.AlterField(
            model_name='signature',
            name='notes',
            field=models.TextField(blank=True, default=None, help_text='Feel free to include anything else you think we should know.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='phone',
            field=models.CharField(blank=True, help_text='Your mobile phone. (Optional)', max_length=255, null=True),
        ),
    ]
