# Generated by Django 3.0.8 on 2020-07-29 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200729_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='homeroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.Homeroom'),
        ),
    ]
