# Generated by Django 3.0.8 on 2020-07-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_district_cd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='cd_status',
            field=models.IntegerField(blank=True, choices=[(10, 'Active'), (20, 'Closed'), (30, 'Merged')], null=True),
        ),
    ]
