# Generated by Django 3.0.8 on 2020-07-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200703_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='app.Account'),
        ),
    ]
