# Generated by Django 3.0.7 on 2020-06-14 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200614_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature', to=settings.AUTH_USER_MODEL),
        ),
    ]
