# Generated by Django 3.0.8 on 2020-07-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_district_cd_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='doc',
            field=models.IntegerField(blank=True, choices=[(0, 'County Office of Education'), (2, 'State Board of Education'), (3, 'Statewide Benefit Charter'), (31, 'State Special Schools'), (34, 'Non-school Location*'), (42, 'Joint Powers Authority (JPA)'), (52, 'Elementary School District'), (54, 'Unified School District'), (56, 'High School District'), (98, 'Regional Occupational Center/Program (ROC/P)')], null=True),
        ),
    ]
