# Generated by Django 3.0.8 on 2020-07-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_registration_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app.Account'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='app.Petition'),
        ),
    ]
