# Generated by Django 3.0.8 on 2020-07-29 14:54

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200729_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roomparent',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'New'), (10, 'Invited'), (20, 'Accepted')], default=0)),
                ('homeroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomparents', to='app.Homeroom')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomparents', to='app.Parent')),
            ],
        ),
    ]
