# Generated by Django 3.0.8 on 2020-07-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_report'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='signature',
            name='unique_signature',
        ),
    ]
