# Generated by Django 3.0.8 on 2020-07-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_roomparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeroom',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homerooms', to='app.School'),
        ),
    ]
