# Generated by Django 3.0.8 on 2020-07-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200703_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='location',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
