# Generated by Django 3.0.7 on 2020-06-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200614_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='district',
            field=models.CharField(blank=True, help_text='Your school district. (Optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='is_doctor',
            field=models.BooleanField(default=False, help_text="If you're a physician please check this box. "),
        ),
        migrations.AlterField(
            model_name='signature',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Name on website.'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text="If you're an educator please check this box. "),
        ),
        migrations.AlterField(
            model_name='signature',
            name='is_volunteer',
            field=models.BooleanField(default=False, help_text="If you're willing to volunteer in some manner please check this box. "),
        ),
        migrations.AlterField(
            model_name='signature',
            name='location',
            field=models.CharField(choices=[('ATH', 'Atherton'), ('BEL', 'Belmont'), ('BRB', 'Brisbane'), ('BUR', 'Burlingame'), ('COL', 'Colma'), ('DC', 'Daly City'), ('EPA', 'East Palo Alto'), ('FC', 'Foster City'), ('HMB', 'Half Moon Bay'), ('HIL', 'Hillsborough'), ('MP', 'Menlo Park'), ('MIL', 'Millbrae'), ('PAC', 'Pacifica'), ('PV', 'Portola Valley'), ('RC', 'Redwood City'), ('SB', 'San Bruno'), ('SC', 'San Carlos'), ('SM', 'San Mateo'), ('SSF', 'South San Francisco'), ('WS', 'Woodside'), ('UN', 'Unincorporated San Mateo County'), ('OUT', 'Outside of San Mateo County')], help_text='Your city. (Required)', max_length=255, null=True),
        ),
    ]
