# Generated by Django 3.0.7 on 2020-06-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200614_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=255)),
                ('answer', models.TextField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='signature',
            name='email',
            field=models.EmailField(help_text="Your email is private and not shared.  It's used to manage preferences and send adminstrative updates. (Required)", max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='is_public',
            field=models.BooleanField(default=False, help_text='List My Name on the Website.'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='name',
            field=models.CharField(help_text="Real name strongly encouraged.  However, if necessary use a descriptor like 'Concerned Parent' or 'Father of Two'. (Required)", max_length=255),
        ),
    ]
