# Generated by Django 3.0.8 on 2020-07-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200710_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.RemoveField(
            model_name='school',
            name='district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
