# Generated by Django 3.0.8 on 2020-07-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200703_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (10, 'Open'), (20, 'Delivered')], default=0),
        ),
    ]
