# Generated by Django 3.0.8 on 2020-07-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200705_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='short',
            new_name='slug',
        ),
    ]
