# Generated by Django 3.0.7 on 2020-06-15 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200615_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
