# Generated by Django 3.0.8 on 2020-07-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_petition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (10, 'Signed'), (20, 'Removed')], default=0),
        ),
    ]
