# Generated by Django 3.0.8 on 2020-07-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200710_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Petition',
            new_name='Organization',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='petition',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='petition',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='signature',
            old_name='petition',
            new_name='organization',
        ),
    ]
