# Generated by Django 3.0.7 on 2020-06-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200615_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
