# Generated by Django 3.0.8 on 2020-07-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200710_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signature',
            new_name='Affiliation',
        ),
    ]
