# Generated by Django 3.0.8 on 2020-07-30 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200729_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='kinds',
            new_name='levels',
        ),
    ]
