# Generated by Django 3.0.8 on 2020-07-10 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200710_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Feel free to include a public message attached to your affiliation.', max_length=512),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='app.Organization'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to=settings.AUTH_USER_MODEL),
        ),
    ]
