# Generated by Django 3.0.8 on 2020-07-30 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200729_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='kind',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='account',
            name='teacher',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(help_text="Pick a school near where you'd like to teach (dosn't have to be your own school; this is just for location.)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='app.School'),
        ),
    ]
