# Generated by Django 3.0.7 on 2020-06-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_faq_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='number',
            new_name='num',
        ),
    ]
