# Generated by Django 3.0.8 on 2020-07-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200729_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_volunteer',
        ),
    ]
