# Generated by Django 3.0.8 on 2020-07-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200705_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='app.District'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petitions', to='app.District'),
        ),
    ]
