# Generated by Django 3.0.8 on 2020-07-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200710_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Feel free to include private notes just for us.', max_length=512),
        ),
    ]
