# Generated by Django 3.0.7 on 2020-06-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200615_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='num',
            field=models.IntegerField(default=50),
        ),
    ]
