# Generated by Django 3.0.8 on 2020-07-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_account_is_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_teacher',
        ),
    ]
