# Generated by Django 3.0.7 on 2020-06-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200615_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Your email will not be used for any purpose other than registration for this Q&A.', max_length=254, unique=True)),
                ('name', models.CharField(help_text='Your name will be used during the Q&A but otherwise will remain private.  Registration for the Q&A DOES NOT signify support for Start Normal.', max_length=255)),
                ('notes', models.TextField(blank=True, max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
