# Generated by Django 3.0.8 on 2020-07-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_account_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_subscribe',
        ),
        migrations.RemoveField(
            model_name='account',
            name='location',
        ),
        migrations.RemoveField(
            model_name='account',
            name='message',
        ),
        migrations.RemoveField(
            model_name='account',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='account',
            name='teacher',
        ),
    ]
