# Generated by Django 3.0.8 on 2020-07-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200706_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.District'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to='app.District'),
        ),
    ]
