# Generated by Django 3.0.7 on 2020-06-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='city',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='handle',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='signature',
            name='message',
            field=models.TextField(blank=True, default=None, help_text='Feel free to include a public message attached to your signature.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='notes',
            field=models.TextField(blank=True, default=None, help_text='Feel free to include anything else you think we should know.', max_length=512, null=True),
        ),
    ]
