# Generated by Django 3.0.8 on 2020-07-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='nomen',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
