# Generated by Django 3.0.8 on 2020-07-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_organization_nomen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Affiliation',
        ),
    ]
