# Generated by Django 3.0.7 on 2020-06-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200617_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='notes',
            field=models.TextField(blank=True, default=None, help_text='Feel free to include private notes just for us.', max_length=512, null=True),
        ),
    ]
