# Generated by Django 3.0.8 on 2020-07-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_affiliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='nomen',
        ),
    ]
