# Generated by Django 3.0.8 on 2020-07-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200729_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='county',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='state',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='zipcode',
        ),
    ]
