# Generated by Django 3.0.8 on 2020-07-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='nces_district_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
