# Generated by Django 3.0.8 on 2020-07-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_organization_nomen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='report',
            name='is_district',
            field=models.BooleanField(default=True),
        ),
    ]
