# Generated by Django 3.0.7 on 2020-06-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='short',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
