# Generated by Django 3.0.8 on 2020-07-30 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200729_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_active',
        ),
    ]
