# Generated by Django 3.0.8 on 2020-07-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_school_nces_district_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='virutal_type',
            new_name='virtual_type',
        ),
    ]
