# Generated by Django 3.0.8 on 2020-07-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200714_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_district',
            field=models.BooleanField(default=True, help_text='Keep this checked if your update applies to the entire school district.  If unsure, keep it checked -- it probably does.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(help_text='This is the main text of your update.  Please stick to the facts as much as possible; we want to inform the public as directly as possible.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(help_text='Give a brief title (ideally no more than five words) for your report.', max_length=100),
        ),
    ]
