# Generated by Django 3.0.8 on 2020-07-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200729_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
