# Generated by Django 3.0.7 on 2020-06-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_district_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='short',
            field=models.CharField(max_length=255),
        ),
    ]
