# Generated by Django 3.0.8 on 2020-07-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200706_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='nces_district_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
