# Generated by Django 3.0.8 on 2020-07-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200714_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.IntegerField(choices=[(410, 'Superintendent'), (420, 'Board President'), (430, 'Board Vice-President'), (440, 'Board Clerk'), (450, 'Board Trustee'), (510, 'Principal')], null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(help_text='Use your own voice, but please stick to the facts as much as possible; we want to be a credible source to all parents.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(help_text='Give a brief title (ideally no more than five words.)', max_length=100),
        ),
    ]
