# Generated by Django 3.0.8 on 2020-07-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_delete_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (10, 'Active')], default=0, null=True),
        ),
    ]
