# Generated by Django 3.0.7 on 2020-06-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200621_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
