# Generated by Django 3.0.8 on 2020-07-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_contact_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
