# Generated by Django 3.0.8 on 2020-07-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200706_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='app.District'),
        ),
    ]
