# Generated by Django 3.0.8 on 2020-07-15 23:50

import app.models
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200715_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from=app.models.get_populate_from, unique=True)),
                ('status', models.IntegerField(choices=[(10, 'Active'), (20, 'Closed'), (30, 'Merged')], default=10)),
                ('kind', models.IntegerField(blank=True, choices=[(400, 'County Office of Education'), (402, 'State Board of Education'), (403, 'Statewide Benefit Charter'), (431, 'State Special Schools'), (434, 'Non-school Location*'), (442, 'Joint Powers Authority (JPA)'), (452, 'Elementary School District'), (454, 'Unified School District'), (456, 'High School District'), (458, 'Community College District'), (498, 'Regional Occupational Center/Program (ROC/P)'), (499, 'Administration Only')], null=True)),
                ('nces_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('zipcode', models.CharField(blank=True, default='', max_length=255)),
                ('county', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.URLField(blank=True, default='')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from=app.models.get_populate_from, unique=True)),
                ('status', models.IntegerField(choices=[(10, 'Active'), (20, 'Closed'), (30, 'Merged')], default=10)),
                ('kind', models.IntegerField(blank=True, choices=[(510, 'Preschool'), (520, 'Elementary'), (530, 'Intermediate/Middle/Junior High'), (540, 'High School'), (550, 'Elementary-High Combination'), (560, 'Adult'), (570, 'Ungraded')], null=True)),
                ('nces_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('zipcode', models.CharField(blank=True, default='', max_length=255)),
                ('county', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.URLField(blank=True, default='')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='app.District')),
            ],
        ),
    ]
