# Generated by Django 3.0.8 on 2020-07-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200730_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_district',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (10, 'Approved'), (20, 'Rejected')], default=0),
        ),
    ]
