# Generated by Django 3.0.8 on 2020-07-15 23:50

from django.db import migrations

def forward(apps, schema_editor):
    District = apps.get_model('app.district')
    Organization = apps.get_model('app.organization')
    olds = Organization.objects.filter(
        kind__range=[400,500],
    )
    for o in olds:
        District.objects.create(
            is_active=o.is_active,
            name=o.name,
            description=o.text,
            slug=o.slug,
            status=o.status,
            kind=o.kind,
            nces_id=o.nces_id,
            address=o.address,
            city=o.city,
            state=o.state,
            zipcode=o.zipcode,
            county=o.county,
            phone=o.phone,
            website=o.website,
            lat=o.lat,
            lon=o.lon,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_district_school'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
