# Generated by Django 3.0.8 on 2020-08-01 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200730_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=254)),
                ('message', models.TextField(blank=True, default='Please join my homeroom.', help_text='Notes.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('homeroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='app.Homeroom')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='school',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transmission',
            name='report',
        ),
        migrations.RemoveField(
            model_name='transmission',
            name='school',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Transmission',
        ),
    ]
