# Generated by Django 3.0.7 on 2020-06-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='position',
            new_name='role',
        ),
    ]
