# Generated by Django 3.0.8 on 2020-07-15 23:57

from django.db import migrations


def forward(apps, schema_editor):
    District = apps.get_model('app.district')
    School = apps.get_model('app.school')
    Organization = apps.get_model('app.organization')
    olds = Organization.objects.filter(
        kind__gte=500,
    )
    for o in olds:
        district = District.objects.get(
            nces_id=o.nces_id,
        )
        School.objects.create(
            is_active=o.is_active,
            name=o.name,
            description=o.text,
            slug=o.slug,
            status=o.status,
            kind=o.kind,
            nces_id=o.nces_id,
            address=o.address,
            city=o.city,
            state=o.state,
            zipcode=o.zipcode,
            county=o.county,
            phone=o.phone,
            website=o.website,
            lat=o.lat,
            lon=o.lon,
            district=district,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200715_1650'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
