# Generated by Django 3.0.8 on 2020-07-16 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200715_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='app.District'),
        ),
        migrations.AddField(
            model_name='report',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='app.District'),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.District'),
        ),
    ]
