# Generated by Django 3.0.8 on 2020-08-01 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200801_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='homeroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='app.Homeroom'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
