# Generated by Django 3.0.7 on 2020-06-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200622_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.District'),
        ),
    ]
