# Generated by Django 3.0.8 on 2020-07-16 02:45

from django.db import migrations

def forward(apps, schema_editor):
    Contact = apps.get_model('app.contact')
    Report = apps.get_model('app.report')
    Student = apps.get_model('app.student')
    District = apps.get_model('app.district')

    contacts = Contact.objects.all()
    for contact in contacts:
        district = District.objects.get(
            nces_id=contact.organization.nces_id,
        )
        contact.district = district
        contact.save()

    reports = Report.objects.all()
    for report in reports:
        district = District.objects.get(
            nces_id=report.organization.nces_id,
        )
        report.district = district
        report.save()

    students = Student.objects.all()
    for student in students:
        district = District.objects.get(
            nces_id=student.organization.nces_id,
        )
        student.district = district
        student.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200715_1941'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
