# Generated by Django 3.0.7 on 2020-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200622_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.IntegerField(blank=True, choices=[(10, 'Superintendent'), (20, 'Board President'), (30, 'Board Vice-President'), (40, 'Board Clerk'), (50, 'Board Trustee')], null=True),
        ),
    ]
