# Generated by Django 3.0.8 on 2020-08-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200801_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invite',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
