# Generated by Django 3.0.8 on 2020-08-02 15:00

from django.db import migrations

def forward(apps, schema_editor):
    Student = apps.get_model('app', 'Student')
    ss = Student.objects.filter(classmates__isnull=False)
    for s in ss:
        s.homeroom = s.classmates.first().homeroom
        s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20200801_1957'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
