# Generated by Django 3.0.7 on 2020-06-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20200622_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='is_masks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='district',
            name='schedule',
            field=models.IntegerField(choices=[(10, 'In-Person'), (20, 'Blended'), (30, 'Distance'), (40, 'Undecided')], default=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
