# Generated by Django 3.0.7 on 2020-06-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200622_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='masks',
            field=models.IntegerField(choices=[(10, 'Required'), (20, 'Optional'), (30, 'Disallowed')], default=10, null=True),
        ),
    ]
