# Generated by Django 3.0.8 on 2020-07-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200716_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='report',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='student',
            name='district',
        ),
        migrations.RemoveField(
            model_name='student',
            name='organization',
        ),
    ]
