# Generated by Django 3.0.8 on 2020-07-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200706_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='county_name',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='county_name',
            new_name='county',
        ),
    ]
