# Generated by Django 3.0.8 on 2020-07-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200706_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='edops_type',
            new_name='edops',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='funding_type',
            new_name='funding',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='grade_span',
            new_name='grades',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='virtual_type',
            new_name='virtual',
        ),
        migrations.RemoveField(
            model_name='school',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_masks',
        ),
        migrations.RemoveField(
            model_name='school',
            name='masks',
        ),
        migrations.RemoveField(
            model_name='school',
            name='meeting_date',
        ),
        migrations.RemoveField(
            model_name='school',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='school',
            name='status',
        ),
    ]
