# Generated by Django 3.0.8 on 2020-07-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200716_0857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
