# Generated by Django 3.0.8 on 2020-08-02 19:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200802_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomparent',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('homeroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asks', to='app.Homeroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asks', to='app.Student')),
            ],
        ),
    ]
