# Generated by Django 3.0.7 on 2020-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_district_masks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='masks',
            field=models.IntegerField(choices=[(0, '(Unkwown)'), (10, 'Required'), (20, 'Optional'), (30, 'Disallowed')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='schedule',
            field=models.IntegerField(choices=[(0, '(Unkwown)'), (10, 'In-Person'), (20, 'Blended'), (30, 'Distance'), (40, 'Undecided')], default=0, null=True),
        ),
    ]
