# Generated by Django 3.0.8 on 2020-08-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20200802_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.IntegerField(blank=True, choices=[(510, 'Preschool'), (520, 'Elementary'), (530, 'Intermediate/Middle/Junior High'), (540, 'High School'), (550, 'Elementary-High Combination'), (560, 'Adult'), (570, 'Ungraded')], null=True),
        ),
    ]
