# Generated by Django 3.0.8 on 2020-07-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20200706_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='district',
            name='is_masks',
        ),
        migrations.RemoveField(
            model_name='district',
            name='masks',
        ),
        migrations.RemoveField(
            model_name='district',
            name='meeting_date',
        ),
        migrations.RemoveField(
            model_name='district',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='district',
            name='status',
        ),
    ]
