# Generated by Django 3.0.8 on 2020-08-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20200802_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.IntegerField(blank=True, choices=[(510, 'Preschool'), (520, 'Elementary'), (530, 'Intermediate/Middle/Junior High'), (540, 'High School'), (550, 'Elementary-High Combination'), (555, 'Secondary'), (560, 'Adult'), (570, 'Ungraded')], null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='nces_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
