# Generated by Django 3.0.8 on 2020-08-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20200803_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='kind',
            field=models.IntegerField(choices=[(0, 'New'), (10, 'Public'), (20, 'Private')], default=0),
        ),
    ]
