# Generated by Django 3.0.8 on 2020-07-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200718_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
