# Generated by Django 3.1 on 2020-08-08 12:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200803_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='geojson',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
