# Generated by Django 3.1 on 2020-08-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_school_geojson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='geojson',
            new_name='geo',
        ),
    ]
