# Generated by Django 3.0.8 on 2020-07-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20200718_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='cd_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='cd_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(400, 'County Office of Education'), (402, 'State Board of Education'), (403, 'Statewide Benefit Charter'), (431, 'State Special Schools'), (434, 'Non-school Location*'), (442, 'Joint Powers Authority (JPA)'), (452, 'Elementary School District'), (454, 'Unified School District'), (456, 'High School District'), (458, 'Community College District'), (470, 'Private'), (498, 'Regional Occupational Center/Program (ROC/P)'), (499, 'Administration Only')], null=True),
        ),
    ]
