# Generated by Django 3.0.8 on 2020-07-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20200718_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='cd_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='cd_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
