# Generated by Django 3.0.8 on 2020-07-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20200706_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='county',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
