# Generated by Django 3.0.8 on 2020-07-07 14:25

import app.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_department_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from=app.models.get_populate_from, unique=True),
        ),
    ]
