# Generated by Django 3.1 on 2020-08-08 13:52

from django.db import migrations

def forward(apps, schema_editor):
    MAP = {
        2: -1,
        5: 0,
        10: 1,
        20: 2,
        30: 3,
        40: 4,
        50: 5,
        60: 6,
        70: 7,
        80: 8,
        90: 9,
        100: 10,
        110: 11,
        120: 12,
    }
    School = apps.get_model('app', 'School')
    ss = School.objects.all()
    for s in ss:
        if s.low_grade:
            s.low_grade = MAP[s.low_grade]
        if s.high_grade:
            s.high_grade = MAP[s.high_grade]
        s.save()

    Student = apps.get_model('app', 'Student')
    ts = Student.objects.all()
    for t in ts:
        if t.grade:
            t.grade = MAP[t.grade]
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20200808_0647'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
