# Generated by Django 3.0.8 on 2020-07-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20200707_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
