# Generated by Django 3.0.8 on 2020-07-19 15:12

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20200719_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.Contact')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.School')),
            ],
        ),
    ]
