# Generated by Django 3.0.8 on 2020-07-08 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_department_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petitions', to='app.District'),
        ),
    ]
