# Generated by Django 3.1 on 2020-08-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20200808_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeroom',
            name='distance',
            field=models.IntegerField(blank=True, choices=[(0, 'No Preference'), (10, 'Required'), (20, 'Optional')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='kind',
            field=models.IntegerField(choices=[(10, 'Public'), (20, 'Private')], default=10),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='masks',
            field=models.IntegerField(blank=True, choices=[(0, 'No Preference'), (10, 'Required'), (20, 'Optional')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='schedule',
            field=models.IntegerField(blank=True, choices=[(0, 'No Preference'), (10, '1-2 Days'), (20, '3-4 Days'), (30, '5 Days')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homeroom',
            name='status',
            field=models.IntegerField(choices=[(10, 'Open'), (20, 'Closed')], default=10),
        ),
    ]
