# Generated by Django 3.1 on 2020-08-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20200809_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeroom',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='homeroom',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
