# Generated by Django 3.0.8 on 2020-07-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20200708_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='app.Department'),
        ),
    ]
