# Generated by Django 3.1 on 2020-08-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20200809_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='distance',
            field=models.IntegerField(blank=True, choices=[(0, 'No Preference'), (10, 'Required'), (20, 'Optional')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='masks',
            field=models.IntegerField(blank=True, choices=[(0, 'No Preference'), (10, 'Required'), (20, 'Optional')], default=0, null=True),
        ),
    ]
