# Generated by Django 3.0.8 on 2020-07-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_signature_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='app.Department'),
        ),
    ]
