# Generated by Django 3.1 on 2020-08-09 14:35

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20200809_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
