# Generated by Django 3.0.8 on 2020-07-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20200719_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
