# Generated by Django 3.0.8 on 2020-07-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20200708_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.IntegerField(blank=True, choices=[(410, 'Superintendent'), (420, 'Board President'), (430, 'Board Vice-President'), (440, 'Board Clerk'), (450, 'Board Trustee'), (510, 'Principal')], null=True),
        ),
    ]
