# Generated by Django 3.0.8 on 2020-07-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20200719_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.IntegerField(choices=[(410, 'Superintendent'), (420, 'Board President'), (430, 'Board Vice-President'), (440, 'Board Clerk'), (450, 'Board Trustee'), (460, 'Administrative'), (510, 'Principal'), (900, 'Unknown')], null=True),
        ),
    ]
