# Generated by Django 3.0.8 on 2020-07-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20200708_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='petition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='app.Petition'),
        ),
    ]
