# Generated by Django 3.1 on 2020-08-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_parent_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='safety',
            field=models.IntegerField(blank=True, choices=[(0, 'No Preference'), (10, 'Standard'), (20, 'Enhanced')], default=0, null=True),
        ),
    ]
