# Generated by Django 3.0.8 on 2020-07-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20200708_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='district',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='district',
        ),
    ]
