# Generated by Django 3.0.8 on 2020-07-21 22:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20200720_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='kinds',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(510, 'Preschool'), (520, 'Elementary'), (530, 'Intermediate/Middle/Junior High'), (540, 'High School'), (550, 'Elementary-High Combination'), (560, 'Adult'), (570, 'Ungraded')], max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='kind',
            field=models.IntegerField(choices=[(510, 'Preschool'), (520, 'Elementary'), (530, 'Intermediate/Middle/Junior High'), (540, 'High School'), (550, 'Elementary-High Combination'), (560, 'Adult'), (570, 'Ungraded')], null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
    ]
