# Generated by Django 3.0.8 on 2020-07-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20200708_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='petition',
        ),
    ]
