# Generated by Django 3.0.8 on 2020-07-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_signature_petition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Petition',
        ),
    ]
