# Generated by Django 3.1 on 2020-08-11 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20200810_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
    ]
