# Generated by Django 3.0.8 on 2020-07-21 23:06

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20200721_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_credential',
            field=models.BooleanField(default=False, help_text='Are you credentialed?'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(help_text="Pick a near where you'd like to teach (dosn't have to be your own school; this is just for location.)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='app.School'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(110, 'English'), (120, 'History'), (130, 'Mathematics'), (140, 'Science'), (150, 'Art'), (160, 'Music'), (170, 'PE'), (180, 'Other')], help_text='What subjects do you teach?', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='kinds',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(510, 'Preschool'), (520, 'Elementary'), (530, 'Intermediate/Middle/Junior High'), (540, 'High School')], help_text='What levels do you teach?', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Please add anything else you think we should know.', max_length=512),
        ),
    ]
