# Generated by Django 3.1 on 2020-08-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20200811_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='parent',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Your mobile phone. (Optional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.school'),
        ),
    ]
