# Generated by Django 3.0.8 on 2020-07-22 15:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20200722_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='slug',
        ),
        migrations.AlterField(
            model_name='cohort',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from='name', unique=True),
        ),
    ]
