# Generated by Django 3.1 on 2020-08-11 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20200811_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='parent_email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ask',
            name='parent_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ask',
            name='student_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ask',
            name='homeroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asks', to='app.homeroom'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asks', to='app.student'),
        ),
    ]
