# Generated by Django 3.0.8 on 2020-07-22 16:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20200722_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subject',
        ),
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(110, 'English'), (120, 'History'), (130, 'Mathematics'), (140, 'Science'), (150, 'Art'), (160, 'Music'), (170, 'PE'), (180, 'Other')], max_length=31, null=True),
        ),
    ]
