# Generated by Django 3.0.8 on 2020-07-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20200722_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='state',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
