# Generated by Django 3.1 on 2020-08-11 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20200811_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
    ]
