# Generated by Django 3.1 on 2020-08-12 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_delete_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roomparent',
        ),
    ]
