# Generated by Django 3.1 on 2020-08-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_delete_roomparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeroom',
            name='goal',
            field=models.IntegerField(choices=[(10, 'Instruction'), (20, 'Social')], default=10),
        ),
    ]
