# Generated by Django 3.1 on 2020-08-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_homeroom_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='status',
            field=models.IntegerField(choices=[(0, 'New')], default=0),
        ),
    ]
