# Generated by Django 3.0.8 on 2020-07-23 13:14

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_auto_20200722_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeroom',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from='name', unique=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (10, 'Active')], default=0)),
                ('grade', models.IntegerField(choices=[(2, 'Transitional Kindergarten'), (5, 'Kindergarten'), (10, 'First  Grade'), (20, 'Second  Grade'), (30, 'Third  Grade'), (40, 'Fourth  Grade'), (50, 'Fifth  Grade'), (60, 'Sixth  Grade'), (70, 'Seventh Grade'), (80, 'Eighth Grade'), (90, 'Ninth Grade'), (100, 'Tenth Grade'), (110, 'Eleventh Grade'), (120, 'Twelfth Grade'), (130, 'Freshman'), (140, 'Sophomore')])),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homerooms', to='app.Parent')),
            ],
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cohort',
        ),
        migrations.DeleteModel(
            name='Cohort',
        ),
        migrations.AddField(
            model_name='classroom',
            name='homeroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='app.Homeroom'),
        ),
        migrations.AddField(
            model_name='invite',
            name='homeroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='app.Homeroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='homeroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.Homeroom'),
        ),
    ]
