# Generated by Django 3.1 on 2020-08-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_ask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='homeroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asks', to='app.homeroom'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'New'), (10, 'Invited')], default=0),
        ),
        migrations.AlterField(
            model_name='ask',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asks', to='app.student'),
        ),
    ]
