# Generated by Django 3.1 on 2020-08-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20200812_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(None, '-- Choose Gender --'), (10, 'Boy'), (20, 'Girl')], null=True),
        ),
        migrations.AddField(
            model_name='ask',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(None, '-- Choose Grade --'), (-1, 'Preschool'), (0, 'Kindergarten'), (1, 'First Grade'), (2, 'Second Grade'), (3, 'Third Grade'), (4, 'Fourth Grade'), (5, 'Fifth Grade'), (6, 'Sixth Grade'), (7, 'Seventh Grade'), (8, 'Eighth Grade'), (9, 'Ninth Grade'), (10, 'Tenth Grade'), (11, 'Eleventh Grade'), (12, 'Twelfth Grade')], null=True),
        ),
        migrations.AddField(
            model_name='ask',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asks', to='app.school'),
        ),
    ]
