# Generated by Django 3.0.8 on 2020-07-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20200723_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeroom',
            name='max_size',
            field=models.IntegerField(default=5),
        ),
    ]
