# Generated by Django 3.1 on 2020-08-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_teacher_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(help_text="Pick a school near where you'd like to teach (doesn't have to be your own school; this is just for location.)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='app.school'),
        ),
    ]
