# Generated by Django 3.0.8 on 2020-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_homeroom_max_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_welcomed',
            field=models.BooleanField(default=False),
        ),
    ]
