# Generated by Django 3.1 on 2020-08-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20200812_0553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
