# Generated by Django 3.1 on 2020-08-14 15:15

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_delete_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='status',
            field=django_fsm.FSMIntegerField(blank=True, choices=[(0, 'New'), (10, 'Invited')], default=0),
        ),
        migrations.AlterField(
            model_name='homeroom',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(10, 'Open'), (20, 'Closed')], default=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (10, 'Active'), (20, 'Closed'), (30, 'Merged')], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'New'), (10, 'Approved'), (20, 'Rejected')], default=0),
        ),
    ]
