# Generated by Django 3.0.8 on 2020-07-25 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20200724_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeroom',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homerooms', to='app.School'),
        ),
    ]
