# Generated by Django 3.1 on 2020-08-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20200814_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeroom',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='homeroom',
            name='masks',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='masks',
        ),
        migrations.RemoveField(
            model_name='school',
            name='cd_id',
        ),
    ]
