# Generated by Django 3.1 on 2020-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20200814_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='safety',
            field=models.IntegerField(choices=[(0, 'No Safety Preference'), (10, 'Standard'), (20, 'Enhanced')], default=0),
        ),
    ]
