# Generated by Django 3.0.8 on 2020-07-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_homeroom_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeroom',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(2, 'Transitional Kindergarten'), (5, 'Kindergarten'), (10, 'First Grade'), (20, 'Second Grade'), (30, 'Third Grade'), (40, 'Fourth Grade'), (50, 'Fifth Grade'), (60, 'Sixth Grade'), (70, 'Seventh Grade'), (80, 'Eighth Grade'), (90, 'Ninth Grade'), (100, 'Tenth Grade'), (110, 'Eleventh Grade'), (120, 'Twelfth Grade'), (130, 'Freshman'), (140, 'Sophomore')], null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(2, 'Transitional Kindergarten'), (5, 'Kindergarten'), (10, 'First Grade'), (20, 'Second Grade'), (30, 'Third Grade'), (40, 'Fourth Grade'), (50, 'Fifth Grade'), (60, 'Sixth Grade'), (70, 'Seventh Grade'), (80, 'Eighth Grade'), (90, 'Ninth Grade'), (100, 'Tenth Grade'), (110, 'Eleventh Grade'), (120, 'Twelfth Grade'), (130, 'Freshman'), (140, 'Sophomore')], null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='high_grade',
            field=models.IntegerField(blank=True, choices=[(2, 'Transitional Kindergarten'), (5, 'Kindergarten'), (10, 'First Grade'), (20, 'Second Grade'), (30, 'Third Grade'), (40, 'Fourth Grade'), (50, 'Fifth Grade'), (60, 'Sixth Grade'), (70, 'Seventh Grade'), (80, 'Eighth Grade'), (90, 'Ninth Grade'), (100, 'Tenth Grade'), (110, 'Eleventh Grade'), (120, 'Twelfth Grade'), (130, 'Freshman'), (140, 'Sophomore')], null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='low_grade',
            field=models.IntegerField(blank=True, choices=[(2, 'Transitional Kindergarten'), (5, 'Kindergarten'), (10, 'First Grade'), (20, 'Second Grade'), (30, 'Third Grade'), (40, 'Fourth Grade'), (50, 'Fifth Grade'), (60, 'Sixth Grade'), (70, 'Seventh Grade'), (80, 'Eighth Grade'), (90, 'Ninth Grade'), (100, 'Tenth Grade'), (110, 'Eleventh Grade'), (120, 'Twelfth Grade'), (130, 'Freshman'), (140, 'Sophomore')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(choices=[(2, 'Transitional Kindergarten'), (5, 'Kindergarten'), (10, 'First Grade'), (20, 'Second Grade'), (30, 'Third Grade'), (40, 'Fourth Grade'), (50, 'Fifth Grade'), (60, 'Sixth Grade'), (70, 'Seventh Grade'), (80, 'Eighth Grade'), (90, 'Ninth Grade'), (100, 'Tenth Grade'), (110, 'Eleventh Grade'), (120, 'Twelfth Grade'), (130, 'Freshman'), (140, 'Sophomore')]),
        ),
    ]
