# Generated by Django 3.1 on 2020-08-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20200814_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='is_welcomed',
            field=models.BooleanField(default=False),
        ),
    ]
