# Generated by Django 3.1 on 2020-08-14 20:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_auto_20200814_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeroom',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='homeroom',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='app_homeroo_search__0b949a_gin'),
        ),
    ]
