# Generated by Django 3.1 on 2020-08-14 22:08

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20200814_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMIntegerField(blank=True, choices=[(0, 'New'), (10, 'Invited'), (20, 'Enrolled')], default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('homeroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classmates', to='app.homeroom')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classmates_inbound', to='app.parent')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classmates_outbound', to='app.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classmates', to='app.student')),
            ],
        ),
    ]
