# Generated by Django 3.1 on 2020-08-14 22:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_classmate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='app_student_search__bd8108_gin'),
        ),
    ]
