# Generated by Django 3.1 on 2020-08-15 21:59

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_auto_20200814_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmate',
            name='homeroom',
        ),
        migrations.RemoveField(
            model_name='classmate',
            name='invitee',
        ),
        migrations.RemoveField(
            model_name='classmate',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='classmate',
            name='student',
        ),
        migrations.AddField(
            model_name='classmate',
            name='from_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classmates_from', to='app.student'),
        ),
        migrations.AddField(
            model_name='classmate',
            name='to_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classmates_to', to='app.student'),
        ),
        migrations.AlterField(
            model_name='classmate',
            name='status',
            field=django_fsm.FSMIntegerField(blank=True, choices=[(0, 'New'), (10, 'Pending'), (20, 'Accepted'), (30, 'Rejected')], default=0),
        ),
    ]
