# Generated by Django 3.1 on 2020-08-15 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20200815_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='from_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classmates_from', to='app.student'),
        ),
        migrations.AlterField(
            model_name='classmate',
            name='to_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classmates_to', to='app.student'),
        ),
    ]
