# Generated by Django 3.1 on 2020-08-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20200815_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='frequency',
            field=models.IntegerField(blank=True, choices=[(0, 'No Frequency Preference'), (10, '1-2 Days'), (20, '3-4 Days'), (30, '5 Days')], default=0),
        ),
        migrations.AlterField(
            model_name='parent',
            name='schedule',
            field=models.IntegerField(blank=True, choices=[(0, 'No Schedule Preference'), (10, 'Morning'), (20, 'Afternoon'), (30, 'Full Day')], default=0),
        ),
    ]
