# Generated by Django 3.1 on 2020-08-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20200827_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(None, '-- Choose Gender --'), (10, 'Boy'), (20, 'Girl')], null=True),
        ),
    ]
